config/routes.rb
Rails.application.routes.draw do
  resources :spaces

end

app/models/space.rb
class Space < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:district, :location, :address, :accomodates, :amenities, :start_time, :end_time, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sthalam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :accomodates %><br>
    <%= f.number_field :accomodates %>
  </div>
  <div class="field">
    <%= f.label :amenities %><br>
    <%= f.text_area :amenities %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Spaces</h1>

<table>
  <thead>
    <tr>
      <th>District</th>
      <th>Location</th>
      <th>Address</th>
      <th>Accomodates</th>
      <th>Amenities</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.district %></td>
        <td><%= space.location %></td>
        <td><%= space.address %></td>
        <td><%= space.accomodates %></td>
        <td><%= space.amenities %></td>
        <td><%= space.start_time %></td>
        <td><%= space.end_time %></td>
        <td><%= space.rate %></td>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New Space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>District:</strong>
  <%= @space.district %>
</p>

<p>
  <strong>Location:</strong>
  <%= @space.location %>
</p>

<p>
  <strong>Address:</strong>
  <%= @space.address %>
</p>

<p>
  <strong>Accomodates:</strong>
  <%= @space.accomodates %>
</p>

<p>
  <strong>Amenities:</strong>
  <%= @space.amenities %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @space.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @space.end_time %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @space.rate %>
</p>

<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>